# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stash}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tony Arcieri"]
  s.date = %q{2010-12-07}
  s.description = %q{Stash maps the facilities provided by data structures servers onto classes which mimic Ruby's built-in types}
  s.email = %q{tony@medioh.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/stash.rb",
    "lib/stash/class_methods.rb",
    "lib/stash/hash.rb",
    "lib/stash/list.rb",
    "lib/stash/redis_adapter.rb",
    "lib/stash/string.rb",
    "spec/hash_spec.rb",
    "spec/list_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/string_spec.rb",
    "stash.gemspec"
  ]
  s.homepage = %q{http://github.com/tarcieri/stash}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Abstract interface to data structures servers}
  s.test_files = [
    "spec/hash_spec.rb",
    "spec/list_spec.rb",
    "spec/spec_helper.rb",
    "spec/string_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<redis-namespace>, ["~> 0.10.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.2.0"])
    else
      s.add_dependency(%q<redis>, ["~> 2.1.0"])
      s.add_dependency(%q<redis-namespace>, ["~> 0.10.0"])
      s.add_dependency(%q<rspec>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<redis>, ["~> 2.1.0"])
    s.add_dependency(%q<redis-namespace>, ["~> 0.10.0"])
    s.add_dependency(%q<rspec>, [">= 2.2.0"])
  end
end

